function palasStream = getPalasStreamFile(fileName)
%% Import data from text file
% Script for importing data from the following text file:
%

% filename: /media/teamlary/Team_Lary_1/gitGubRepos/Lakitha/mintsAirML/firmware/dataProcessing/palasStream/200713_144702_Log.txt
%
% Auto-generated by MATLAB on 14-Jul-2020 20:14:24

%% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 103);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = "\t";

    % Specify column names and types
    opts.VariableNames = ["Date", "Time", "PM10", "PM4", "PM25", "PM1", "PMtot", "Cn", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46", "VarName47", "VarName48", "VarName49", "VarName50", "VarName51", "VarName52", "VarName53", "VarName54", "VarName55", "VarName56", "VarName57", "VarName58", "VarName59", "VarName60", "VarName61", "VarName62", "VarName63", "VarName64", "VarName65", "VarName66", "VarName67", "VarName68", "VarName69", "VarName70", "VarName71", "VarName72", "VarName73", "VarName74", "VarName75", "VarName76", "VarName77", "VarName78", "VarName79", "VarName80", "VarName81", "VarName82", "VarName83", "VarName84", "VarName85", "VarName86", "VarName87", "VarName88", "VarName89", "VarName90", "VarName91", "VarName92", "VarName93", "VarName94", "VarName95", "VarName96", "VarName97", "VarName98", "VarName99", "VarName100", "VarName101", "VarName102", "VarName103"];
    opts.VariableTypes = ["datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, "VarName103", "WhitespaceRule", "preserve");
    opts = setvaropts(opts, "VarName103", "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "Date", "InputFormat", "dd.MM.yy");
    opts = setvaropts(opts, "Time", "InputFormat", "HH:mm:ss");

    % Import the data
    preTable = readtable(fileName, opts);
    dateTimePMPre = strcat(string(preTable.Date),"~",string(preTable.Time));
    dateTimePM     = datetime(dateTimePMPre,'InputFormat','dd.MM.yy~HH:mm:ss','TimeZone','UTC');
    %% Converting to a timetable

    palasStream = [table(dateTimePM),preTable(:,3:102)];
    palasStream.Properties.VariableNames =...
            [{'dateTime'} {'pm10_palas'} {'pm4_palas'} {'pm2_5_palas'} {'pm1_PALAS'} {'pmTotal_palas'} {'dCn_palas'} ...
             {'bin01_palas'} {'bin02_palas'} {'bin03_palas'} {'bin04_palas'} {'bin05_palas'} {'bin06_palas'} {'bin07_palas'} {'bin08_palas'} {'bin09_palas'} {'bin10_palas'} ...  
             {'bin11_palas'} {'bin12_palas'} {'bin13_palas'} {'bin14_palas'} {'bin15_palas'} {'bin16_palas'} {'bin17_palas'} {'bin18_palas'} {'bin19_palas'} {'bin20_palas'} ...  
             {'bin21_palas'} {'bin22_palas'} {'bin23_palas'} {'bin24_palas'} {'bin25_palas'} {'bin26_palas'} {'bin27_palas'} {'bin28_palas'} {'bin29_palas'} {'bin30_palas'} ...  
             {'bin31_palas'} {'bin32_palas'} {'bin33_palas'} {'bin34_palas'} {'bin35_palas'} {'bin36_palas'} {'bin37_palas'} {'bin38_palas'} {'bin39_palas'} {'bin40_palas'} ...  
             {'bin41_palas'} {'bin42_palas'} {'bin43_palas'} {'bin44_palas'} {'bin45_palas'} {'bin46_palas'} {'bin47_palas'} {'bin48_palas'} {'bin49_palas'} {'bin50_palas'} ...  
             {'bin51_palas'} {'bin52_palas'} {'bin53_palas'} {'bin54_palas'} {'bin55_palas'} {'bin56_palas'} {'bin57_palas'} {'bin58_palas'} {'bin59_palas'} {'bin60_palas'} ...  
             {'bin61_palas'} {'bin62_palas'} {'bin63_palas'} {'bin64_palas'} {'bin65_palas'} {'bin66_palas'} {'bin67_palas'} {'bin68_palas'} {'bin69_palas'} {'bin70_palas'} ...  
             {'bin71_palas'} {'bin72_palas'} {'bin73_palas'} {'bin74_palas'} {'bin75_palas'} {'bin76_palas'} {'bin77_palas'} {'bin78_palas'} {'bin79_palas'} {'bin80_palas'} ...  
             {'bin81_palas'} {'bin82_palas'} {'bin83_palas'} {'bin84_palas'} {'bin85_palas'} {'bin86_palas'} {'bin87_palas'} {'bin88_palas'} {'bin89_palas'} {'bin90_palas'} ...  
             {'bin91_palas'} {'bin92_palas'} {'bin93_palas'}  {'bin94_palas'}];

    palasStream(palasStream.pmTotal_palas==0,:)=[];

end
